# Generated by Django 4.2.3 on 2023-07-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_visit_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Revision',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='schedule',
            new_name='revision',
        ),
    ]
