# Generated by Django 4.2.3 on 2023-07-06 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_schedule_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='name',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
