# Generated by Django 4.2.3 on 2023-07-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_visit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='name',
            new_name='user_id',
        ),
    ]
