# Generated by Django 4.2.3 on 2023-07-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_rename_name_visit_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='revision',
        ),
        migrations.AddField(
            model_name='visit',
            name='revisions',
            field=models.ManyToManyField(to='schedule.revision'),
        ),
    ]
